version: '3.6'
services:
  db:
    image: postgres:alpine3.18
    container_name: instagramdatabase
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - instagramdata:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v2.28.0-beta.1-ce.ubuntu
    container_name: instagram_hasura_engine
    ports:
      - ${HASURA_GRAPHQL_PORT}:${HASURA_GRAPHQL_PORT} 
    depends_on:
      - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${ADMIN_SECRET}
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonimous
      HASURA_GRAPHQL_SERVER_PORT: ${HASURA_GRAPHQL_PORT}
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"thisinstagramprojecthasthistypeofjwtsecretkeytohashtheuseridentity"}'
      ACTION_BASE_URL: ${ACTION_BASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE_AUTH: "true"
    volumes:
      - /hasura/hasura-metadata
volumes:
  instagramdata:
